#!/bin/sh

FTPHOST=${FTPHOST:=http://ftp.freebsd.org/pub/FreeBSD/releases/$(uname -m)}
LIBDIR=${LIBDIR:=/usr/local/lib/fortress}
LOCALCONF_DIR=${LOCALCONF_DIR:=/usr/local/etc/fortress}

SETS="base.txz lib32.txz src.txz"

PV=$(which pv)

INSTALL_CONFIG=/usr/local/etc/fortress.conf
CONFIG=$INSTALL_CONFIG

if [ "x$1" = "x-f" ]; then
	CONFIG=$2
	shift; shift
fi

if [ "x$1" = "x-X" ]; then
	set -x
	shift
fi

	
if [ -f $CONFIG ]; then
	. $CONFIG
else
	# stderr is not defined yet, so we can't call it
	echo "No configuration found. Copy $INSTALL_CONFIG.sample to $INSTALL_CONFIG and edit it before running fortress" >&2
	exit 1
fi

. $LIBDIR/utils.sh

usage()
{
	stderr $0 "[setup|create|destroy|list|start|stop|restart|startall|stopall|update|upgrade|etcupdate|console|rfs|rjc]"
}

setup()
{
	needsroot

	zfs list $DATASET > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		if confirm_prompt false "fortress dataset '$DATASET' does not exist. Should I create it?"; then
			stderr Creating $DATASET
			checkrc zfs create -po mountpoint=$MOUNTPOINT $DATASET
		else
			stderr Need to create dataset $DATASET
			exit 1
		fi
	fi


	FS="jails sets/$RELEASE release/$RELEASE/root"
	
	for F in $FS
	do
		zfs list $DATASET/$F > /dev/null 2>&1
		if [ $? -ne 0 ]; then 
			stderr Creating $DATASET/$F
			checkrc zfs create -p $DATASET/$F
		fi
	done

	MP=$(mp $DATASET/sets/$RELEASE)
	RMP=$(mp $DATASET/release/$RELEASE)
	if [ "x$MP" = "x" ]; then
		stderr "MP Undefined, something bad happened"
		exit 1
	fi
	for SET in $SETS
	do
		if [ ! -f $MP/$SET ]; then
			stderr Fetching $MP/$SET
			checkrc fetch -o $MP/$SET $FTPHOST/$RELEASE/$SET
		fi
	done
	
	for SET in $SETS
	do
		if [ -f $RMP/.fortress_extracted_$SET ]; then
			continue
		fi

		PROGBAR="cat"
		if [ ! -z ${PV:+is_set} ]; then
			PROGBAR="$PV -s $(stat -f %z $MP/$SET)"
		fi

		stderr Extracting $MP/$SET in $RMP/root
		cat $MP/$SET | $PROGBAR | tar -C $RMP/root -xJf-
		
		touch $RMP/.fortress_extracted_$SET
	done
	
	if [ ! -d $RMP/root/etcupdate ]; then
		mkdir $RMP/root/etcupdate
	fi
	
	stderr Checking for $RMP/root/etcupdate
	if [ ! -f $RMP/root/etcupdate/etcupdate-$RELEASE.tbz ]; then
		stderr Creating etcupdate-$RELEASE.tbz
		mount -t devfs devfs $RMP/root/dev
		chroot $RMP/root etcupdate build /etcupdate/etcupdate-$RELEASE.tbz
		umount $RMP/root/dev
	fi
	stderr Fortress setup complete
	touch $(mp $DATASET)/.fortress_setup_complete
}

create()
{
	needsroot

	local name=${1:?jail name is required}

	load_local_overrides $name
	
	zfs list $DATASET/jails/$name > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		stderr "Jail $name already exists"
		return
	fi
	
	echo Creating jail dataset
	zfs create $DATASET/jails/$name
	zfs create $DATASET/jails/$name/root
	
	local MP=$(mp $DATASET/jails/$name)
	
	echo Creating jail root directories
	for _d in $MOUNT; do
		mkdir -p $MP/root/$_d
	done
	
	local RMP=$(mp $DATASET/release/$RELEASE/root)

	echo Copying /etc
	cd $RMP/etc && find . | cpio -dp --quiet $MP/root/etc

	echo Copying /root
	cd $RMP/root && find . | cpio -dp --quiet $MP/root/root

	if [ -f /etc/localtime ]; then
		echo Copying /etc/localtime
		cp /etc/localtime $MP/root/etc
	else
		stderr /etc/localtime does not exist
	fi

	echo Creating /etc/rc.conf
	cat > $MP/root/etc/rc.conf <<EOF
hostname=$name
cron_flags="-J 15"

# Disable Sendmail by default
sendmail_enable="NONE"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

# Run secure syslog
syslogd_flags="-c -ss"
EOF

	local OLDIFS=$IFS
	export IFS=
	echo "$RC_CONF" | while read -r line; do
		sysrc -f $MP/root/etc/rc.conf $line
	done
	export IFS=$OLDIFS

	echo Creating /etc/resolv.conf
	if [ ! -z ${RESOLV_CONF:+is_set} ]; then
		cat > $MP/root/etc/resolv.conf <<EOF
$RESOLV_CONF
EOF
	fi
	
	echo Extracting etcupdate-$RELEASE.tbz
	mount_jail $MP/root
	chroot $MP/root etcupdate extract -t /etcupdate/etcupdate-$RELEASE.tbz
	umount_jail $MP/root

	echo Writing jail.conf
	create_jailconf $name $MP 


	echo Writing fstab
	create_fstab $name $RMP $MP

	echo Jail created
}

rewrite_jail_conf()
{
	needsroot

	local name=${1:?jail name is required}
	MP=$(mp $DATASET/jails/$name)

	echo Writing jail.conf
	create_jailconf $name $MP 
}

rewrite_fstab()
{
	needsroot

	local name=${1:?jail name is required}
	local RMP=$(mp $DATASET/release/$RELEASE/root)
	local MP=$(mp $DATASET/jails/$name)

	echo Writing fstab
	create_fstab $name $RMP $MP
}

destroy()
{
	needsroot

	local name=${1:?jail name is required}

	jls -j $name >/dev/null 2>&1
	if [ $? -eq 0 ]; then
		stop $name
	fi
	
	MP=$(mp $DATASET/jails/$name)
	
	echo -n "Are you sure you want to destroy $MP? [y/N]: "
	read RESP
	RESP=${RESP:-N}
	if [ $RESP = 'y' -o $RESP = 'Y' ]; then
		#zfs destroy $DATASET/jails/$name/root
		zfs destroy -rf $DATASET/jails/$name
	fi

	local cfg=/usr/local/etc/fortress/$name.conf
	if [ -f $cfg ]; then
		echo -n "Delete $cfg? [y/N]: "
		read RESP
		RESP=${RESP:-N}
		if [ $RESP = 'y' -o $RESP = 'Y' ]; then
			rm $cfg
		fi
	fi
}


list()
{
	(echo JID IP NAME MOUNTPOINT RUNNING
	get_jail_names mountpoint | while read -r name mp; do
		JID=$(jls -j $name -qn jid 2>/dev/null | cut -f2 -d=)

		if [ "x$JID" != "x" ]; then
			IP=$(jexec $name ifconfig e0b_$name 2>/dev/null | awk '/inet /{print $2}')
			if [ "x$IP" = "x" ]; then
				_ip=$(ip_from_rc_conf $name $mp)
				IP=${_ip:="??.??.??.??"}
			fi
			RUNNING=yes
		else
			_ip=$(ip_from_rc_conf $name $mp)
			IP=${_ip:=n/a}
			RUNNING=no
			JID=n/a
		fi
		echo $JID $IP $name $mp $RUNNING
	done) | column -t
}

needsjib()
{
	if [ ! -x $JIB ]; then
		stderr "fortress requires $JIB to exist and be executable. If jib exists in a different location, set it in $CONFIG"
		exit 1
	fi
}

start()
{
	needsroot
	needsjib

	local name=${1:?jail name is required}

	MP=$(mp $DATASET/jails/$name)
	echo Starting $name...
	jail -qcf $MP/jail.conf
}

stop()
{
	needsroot
	needsjib

	local name=${1:?jail name is required}

	MP=$(mp $DATASET/jails/$name)
	echo Stopping $name...
	jail -qrf $MP/jail.conf $name
}

update()
{
	needsroot

	ZR=$DATASET/release/$RELEASE/root
	R=$(mp $ZR)
	CMD="/usr/sbin/freebsd-update -b $R -d $R/var/db/freebsd-update/ -f $R/etc/freebsd-update.conf --not-running-from-cron"

	zfs list $ZR@pre-update >/dev/null 2>&1
	ret=$?
	if [ $ret -eq 0 ]; then
		stderr "$ZR@pre-update already exists. Delete it first."
		exit $ret
	fi

	zfs snap $ZR@pre-update
	ret=$?
	if [ $ret -ne 0 ]; then
		stderr "Error taking snapshot"
		exit $ret
	fi

	PAGER=cat $CMD fetch 
	$CMD install 
	if [ $? -eq 0 ]; then
		# rebuild etcupdate-$RELEASE.tbz
		mount -t devfs devfs $R/dev
		chroot $R etcupdate build /etcupdate/etcupdate-$RELEASE.tbz
		umount $R/dev
		echo "Updates installed. Restart jails then run 'fortress.sh etcupdate jail1 jail2 ... jailN'"
	else
		echo "No updates to install"
	fi
}

upgrade()
{
	needsroot

	local name=${1:?jail name is required}
	local MP=$(mp $DATASET/jails/$name)

	load_local_overrides $name

	echo -n "About to upgrade jail '$name' to '$RELEASE,' is this correct? [y/N]: "
	read RESPONSE
	case $RESPONSE in
		[Yy]|[Yy][Ee][Ss])
			setup
			stop $name
			rewrite_fstab $name
			mount_jail $MP/root
			etcupdate $name
			umount_jail $MP/root
			start $name
			;;
		*)
			exit
			;;
	esac
}

etcupdate()
{
	for jail in $@
	do
		local MP=$(mp $DATASET/jails/$jail)
		chroot $MP/root /usr/sbin/etcupdate -F -t /etcupdate/etcupdate-$RELEASE.tbz
		chroot $MP/root /usr/sbin/etcupdate resolve
	done
	echo "etcupdate complete. Restart jail(s)"
}

startall()
{
	get_jail_names mountpoint | while read -r jail mp; do
		if [ -f $mp/NOAUTO ]; then
			stderr "Skipping $jail because $mp/NOAUTO exists"
			continue
		else
			start $jail
		fi
	done
}


stopall()
{
	get_jail_names | while read -r jail; do
		jls -j $jail >/dev/null 2>&1
		if [ $? -eq 0 ]; then
			stop $jail
		else
			echo "$jail not running"
		fi
	done
}

main()
{
	if [ $(setupcomplete) = "1" ]; then
		case $1 in 
			create)
				shift
				create $@
				;;
			destroy)
				shift
				destroy $@
				;;
			list)
				shift
				list $@
				;;
			start)
				shift
				start $@
				;;
			startall)
				shift
				startall $@
				;;
			stopall)
				shift
				stopall $@
				;;
			stop)
				shift
				stop $@
				;;
			restart)
				shift
				stop $@
				start $@
				;;
			update)
				shift
				update $@
				;;
			upgrade)
				shift
				upgrade $@
				;;
			etcupdate)
				shift
				etcupdate $@
				;;
			console)
				shift
				if ! is_running $1; then
					start $1
				fi
				jexec -l $1 /bin/csh
				;;
			rjc)
				shift
				rewrite_jail_conf $@
				;;
			rfs)
				shift
				rewrite_fstab $@
				;;
			*)
				if [ ! -z $1 ]; then 
					stderr unknown command $1
				fi
				usage
				;;
		esac
	else
		if [ "x$1" = "xsetup" ]; then
			shift
			setup $@
		else
			stderr
			stderr Configure $CONFIG then run \'$0 setup\'
			stderr 
		fi
	fi
}

main $@
